import { User, Match, Message } from "./api";

export const MOCK_USER: User = {
  id: "user_me",
  name: "Maria Santos",
  age: 28,
  location: "Luanda, Angola",
  work: "Engenheira de Software",
  bio: "Amo viajar, conhecer novos lugares e aproveitar a vida! 🌍✨ Adoro música, dançar kizomba e experimentar novas culinárias angolanas.",
  photos: [
    "https://images.unsplash.com/photo-1557296387-5358ad7997bb?w=800",
    "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800",
  ],
  is_verified: 1,
  education: "Universidade Agostinho Neto",
  hometown: "Luanda",
  interests: ["Kizomba", "Tecnologia", "Viagens", "Culinária", "Fotografia"],
};

export const MOCK_PROFILES: User[] = [
  {
    id: "user_ana",
    name: "Ana Silva",
    age: 26,
    location: "Luanda, Angola",
    work: "Designer Gráfica",
    bio: "Apaixonada por arte, design e café ☕️ Adoro explorar novos lugares em Luanda e criar coisas bonitas!",
    photos: [
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=800",
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800",
    ],
    is_verified: 1,
    education: "Instituto Superior de Artes",
    hometown: "Benguela",
    interests: ["Arte", "Design", "Café", "Música", "Dança"],
  },
  {
    id: "user_sofia",
    name: "Sofia Costa",
    age: 24,
    location: "Benguela, Angola",
    work: "Professora",
    bio: "Amo dançar kizomba e semba! 💃 Professora durante o dia, dançarina à noite.",
    photos: [
      "https://images.unsplash.com/photo-1619194617426-f460de77ff72?w=800",
      "https://images.unsplash.com/photo-1589156229687-496a31ad1d1f?w=800",
    ],
    is_verified: 1,
    education: "Escola de Dança de Benguela",
    hometown: "Benguela",
    interests: ["Kizomba", "Semba", "Educação", "Crianças", "Música"],
  },
  {
    id: "user_joana",
    name: "Joana Mendes",
    age: 29,
    location: "Huambo, Angola",
    work: "Engenheira Civil",
    bio: "Aventureira e amante da natureza 🏞️ Sempre pronta para uma nova aventura!",
    photos: [
      "https://images.unsplash.com/photo-1560114928-40f1f1eb26a0?w=800",
      "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800",
    ],
    is_verified: 1,
    education: "ISPT Angola",
    hometown: "Huambo",
    interests: ["Natureza", "Aventura", "Engenharia", "Caminhadas", "Fotografia"],
  },
  {
    id: "user_isabel",
    name: "Isabel Fernandes",
    age: 27,
    location: "Lobito, Angola",
    work: "Fotógrafa",
    bio: "Capturo momentos e crio memórias 📸 Amo a cultura angolana e suas belezas!",
    photos: [
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800",
      "https://images.unsplash.com/photo-1557296387-5358ad7997bb?w=800",
    ],
    is_verified: 1,
    education: "Escola de Artes de Luanda",
    hometown: "Lobito",
    interests: ["Fotografia", "Arte", "Cultura", "Viagens", "Cinema"],
  },
  {
    id: "user_beatriz",
    name: "Beatriz Santos",
    age: 25,
    location: "Luanda, Angola",
    work: "Médica",
    bio: "Médica apaixonada pela vida! 🩺 Amo a praia e os pôr do sol em Luanda.",
    photos: [
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800",
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=800",
    ],
    is_verified: 1,
    education: "Faculdade de Medicina - UAN",
    hometown: "Luanda",
    interests: ["Medicina", "Saúde", "Praia", "Leitura", "Culinária"],
  },
  {
    id: "user_carolina",
    name: "Carolina Lopes",
    age: 28,
    location: "Benguela, Angola",
    work: "Economista",
    bio: "Economista e empreendedora 💼 Sonho grande e trabalho duro!",
    photos: [
      "https://images.unsplash.com/photo-1589156229687-496a31ad1d1f?w=800",
      "https://images.unsplash.com/photo-1619194617426-f460de77ff72?w=800",
    ],
    is_verified: 1,
    education: "Universidade Católica de Angola",
    hometown: "Benguela",
    interests: ["Negócios", "Empreendedorismo", "Economia", "Viagens", "Moda"],
  },
];

export const MOCK_MATCHES: Match[] = [
  {
    match_id: "match_1",
    matched_at: new Date().toISOString(),
    id: "user_ana",
    name: "Ana Silva",
    age: 26,
    location: "Luanda, Angola",
    photos: ["https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200"],
    lastMessage: "Oi! Como está? 😊",
    unread: true,
  },
  {
    match_id: "match_2",
    matched_at: new Date().toISOString(),
    id: "user_sofia",
    name: "Sofia Costa",
    age: 24,
    location: "Benguela, Angola",
    photos: ["https://images.unsplash.com/photo-1619194617426-f460de77ff72?w=200"],
    lastMessage: "Adorei o match! Vamos conversar?",
    unread: true,
  },
];

export const MOCK_MESSAGES: Message[] = [
  { id: 1, match_id: "match_1", sender_id: "user_ana", text: "Oi! Como está? 😊", created_at: new Date(Date.now() - 300000).toISOString() },
  { id: 2, match_id: "match_1", sender_id: "user_me", text: "Olá! Estou bem, obrigada! E você?", created_at: new Date(Date.now() - 240000).toISOString() },
  { id: 3, match_id: "match_1", sender_id: "user_ana", text: "Também estou bem! Vi que você gosta de tecnologia, que interessante!", created_at: new Date(Date.now() - 180000).toISOString() },
  { id: 4, match_id: "match_1", sender_id: "user_me", text: "Sim! É minha paixão. Trabalho como engenheira há 4 anos 😊", created_at: new Date(Date.now() - 120000).toISOString() },
  { id: 5, match_id: "match_1", sender_id: "user_ana", text: "Que legal! Adorei o teu perfil!", created_at: new Date(Date.now() - 60000).toISOString() },
];
