name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # Altere para 'master' se for o nome da sua branch principal
  # Permite correr o workflow manualmente no separador "Actions"
  workflow_dispatch:

permissions:
  contents: write # Necessário para a action fazer push na branch gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        working-directory: ./frontend
        run: npm install

      - name: Compilar a aplicação (Build)
        working-directory: ./frontend
        run: npm run build

      - name: Fazer Deploy na branch gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages